### ISSUE TITLE
Wrong number of security updates

### ISSUE THREAD

**Issue by michag86** [rk4an/psiandroid#36]
PSIAndroid shows a wrong value for security updates:

`<Plugin_UpdateNotifier><UpdateNotifier><packages>24</packages><security>0</security></UpdateNotifier></Plugin_UpdateNotifier>`

michael@hostxyz:~$ cat /var/lib/update-notifier/updates-available 

24 Software-Pakete können aktualisiert werden.
0 Aktualisierungen sind Sicherheitsaktualisierungen.

![screenshot_2015-02-18-21-19-16](https://cloud.githubusercontent.com/assets/6691165/6256060/48e731e6-b7b5-11e4-8add-646b9d5c02f3.png)

--------------------------------------------------------------------
`<Plugin_UpdateNotifier><UpdateNotifier><packages>24</packages><security>9</security></UpdateNotifier></Plugin_UpdateNotifier>`

michael@hostxyz:~$ cat /var/lib/update-notifier/updates-available 

24 Software-Pakete können aktualisiert werden.
9 Aktualisierungen sind Sicherheitsaktualisierungen.

![screenshot_2015-02-18-21-20-29](https://cloud.githubusercontent.com/assets/6691165/6256058/4019c254-b7b5-11e4-9994-fb655ec12cf4.png)

--------------------------------------------------------------------
`<Plugin_UpdateNotifier><UpdateNotifier><packages>25</packages><security>9</security></UpdateNotifier></Plugin_UpdateNotifier>`

michael@hostxyz:~$ cat /var/lib/update-notifier/updates-available 

25 Software-Pakete können aktualisiert werden.
9 Aktualisierungen sind Sicherheitsaktualisierungen.

![screenshot_2015-02-18-21-21-52](https://cloud.githubusercontent.com/assets/6691165/6256065/52156e04-b7b5-11e4-8dc6-79e2700dbd3b.png)

**Comment by rk4an** [comment]
Hi,

Thanks for the report, I will look at this this weekend and fix it :+1:

**Comment by rk4an** [comment]
@michag86 can I send you a testing release with the
