### ISSUE TITLE
Feature: network speed

### ISSUE THREAD

**Issue by ouafnico** [rk4an/psiandroid#38]
Hello

can you add network speed info? On last github version of phpsysinfo we can have the network speed.

Thanks ;)

**Comment by rk4an** [comment]
Hi, I will add it for the next release, thanks.

**Comment by rk4an** [comment]
Release on PlayStore (available in few hours) https://twitter.com/phpsysinfo/status/680821662368010241

**Comment by ouafnico** [comment]
Very nice and quick release :p
